### ISSUE TITLE
Plen2 is not working properly.

### ISSUE THREAD

**Issue by ghost** [plenprojectcompany/PLEN2#3]
I have bought Vivi robot from Aliexpress, I have control the robot with android mobile phone.But they always disconnected even we have test with many mobile phone.
And sometime they can work ,when we push bow ,the robot operate and fall down. If we control the step forward  continuous they hang out and disconnected. Sometime , when we start the robot push on the switch all the servo twist.

**Comment by Guvalif** [comment]
@rkdelhi92
vivi robot is a forked project from PLEN2 official. Unfortunately we can't support the project.
Please contact vivi robot official team.
